name: medboss
description: A new Flutter project.
version: 0.0.1+9

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^3.2.1
  bloc_concurrency: ^0.2.1
  bloc_test: ^9.1.1
  drift: ^2.8.0
  collection: ^1.17.0
  core:
    path: packages/core
  cool_alert: ^2.0.1
  cached_network_image: ^3.2.1
  dio: ^5.0.0
  drift_dev:
  sqlite3_flutter_libs: ^0.5.13
  design:
    path: packages/design
  equatable: ^2.0.3
  flutter_easyloading: ^3.0.5
  flutter_bloc: ^8.1.2
  flutter_bounce: ^1.1.0
  flutter_svg: ^2.0.6
  flutter_wizard: ^2.0.5
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_windowmanager: ^0.2.0
  flutter_keyboard_visibility: ^5.2.0
  flutter_cached_pdfview: ^0.4.1
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  flutter_animate: ^4.1.1+1
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  go_router: ^7.0.2
  google_mobile_ads: ^3.0.0
  http_parser: ^4.0.1
  json_annotation: ^4.7.0
  network:
    path: packages/network
  lottie: ^2.3.2
  iconly: ^1.0.1

  iconsax: ^0.0.8
  provider: ^6.0.3
  photo_view: ^0.14.0
  path_provider: ^2.0.9
  pdftron_flutter: ^1.0.1-13
  parse_server_sdk_flutter: ^5.0.0
  expandable_page_view: ^1.0.17
  reactive_forms: ^14.3.0
  babstrap_settings_screen: ^0.1.5+1
  shared_preferences: ^2.0.11
  smooth_page_indicator: ^1.1.0
  share_plus: ^7.0.1
  responsive_framework: ^0.2.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  built_value_generator: ^8.4.2
  dependency_validator: ^3.0.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
dependency_overrides:
  intl: ^0.18.1
  path_provider_android: 2.0.11

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/logo/
    - assets/svg/

  fonts:
    - family: almarai
      fonts:
        - asset: assets/fonts/almarai/almarai-bold.ttf
        - asset: assets/fonts/almarai/almarai-extra-bold.ttf
        - asset: assets/fonts/almarai/almarai-light.ttf
        - asset: assets/fonts/almarai/almarai-regular.ttf

flutter_intl:
  enabled: true